server:
  port: 3000

spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/devbid_test
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        default_batch_fetch_size: 100
  mvc:
    hidden method:
      filter:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      # 일단 Redis 없이 구현하기 위함.
      timeout: 2000ms

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET:aws-s3-bucket-devbid}
      region: ${AWS_REGION:eu-north-1}
    cloudfront:
      domain: ${AWS_CLOUDFRONT_DOMAIN:dqtqfyr92dz08.cloudfront.net}
    credentials:
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}
    stack:
      auto: false

logging:
  level:
    p6spy: INFO
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: ERROR